### ISSUE TITLE
src/app_httpd.cpp:22:10: fatal error: fd_forward.h: No such file or directory

### ISSUE THREAD

**Issue by LEDZB** [maxgerhardt/pio-esp32cam#1]
Hello, I use your project, but I encountered a problem when compiling. Do you know how to solve it

src/app_httpd.cpp:22:10: fatal error: fd_forward.h: No such file or directory

**Comment by kleinlaut** [comment]
The project was obviously finished unfinished. After I solved this error (the missing file and others) are after the Arduino IDE installation in my environment (Windows 10) under "C:\Users\Name\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\tools\sdk\include\esp-face". You can just copy them into the "include". But then you seem to have to take the face detection out of app_httpd.cpp. Unfortunately, that's beyond my skill level. Too bad, that's exactly what I was looking for.

**Comment by maxgerhardt** [comment]
This project was created 3 years ago and was working then. Now it doesn't work with the most recent Arduino-ESP32 anymore (in its current source code form, of course we could update).

So I just pointed the PlatformIO config to use the older platform where it compiles fine. Fixed per https://github.com/maxgerhardt/pio-esp32cam/commit/07bf521615cfb98105e3316626a735931821b2df
